Wrap deprecated Thread.isAlive
Fix "AttributeError: 'AsyncWorker' object has no attribute 'isAlive'" caused by `isAlive` being deprecated and removed in Python >= 3.9.